language: go
go:
- master
addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
- go get github.com/gohugoio/hugo
script:
- cd src
- hugo
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token:
    secure: YK9sXxpFAOHv1/vOp7V3g4ZXcGD5r3kyMv+G4kAfXjka5rZ6vF3hosWavbKoJDoyMSQIPtwA2tMdBD467am7dWKgG8cXTb8f+S2Zu87ReDnR1dvKFjO+WtG4C3dQFdoivyh71QCDJrMtzozq54tMHdyC2nie/7qEbXtpJKP9IHv6vT5MGh7IrLe/15DHz5zyEfyFIB4M2U6ipy47WujCeNPsMnXTlSJ5ollVRpgos4PbaJ/4IheSx/1fcbGdj5PJH1lXXWg7HnR1EkaqwAQX2IDYwWBjVHLptkxCO+8r9I1UsIE9RghTn3IF7RBD9QtaQxw/xl99gvaSN66VA0HhdcRiTAr3W6qMyToqvAH4plVKaju5rU0Tw9jw9whSS6ZrmCksv/Vf3jucTNFFTu3KoSkFNeGyQtiQCiTb8ylB9Uk4gFFZz7IaGMCvES8tNi0vaQs1XGqTIJsyuCFUwsBln6ic1Tjo6l6w4suQfo6TyR61H91QPfIY+G8wxvXs0Rvb0GB2QoRBV+m0Quyxmp2nuqOOqsv7kdgUtNhX+XEWsuTFVHCXNizuecOrD7DxYyvR09wyN9ZFpbSYxb4cXR4rPQrflmGLTf2ntAUMVg6rcm9uOqVaRHFcR6TsIPvl5Cc9nyufZdhYl2+ZUoSRwBKGJr2HGOhKKNgvVjk0jqNPse0=
  on:
    branch: master
